#! /usr/bin/env python3

import click
from libtb.util import read_config, pull_host_lists, process_whitelist
from libtb.inlet import Inlet
from libtb.sieve import Filters
from libtb.processor import Processor


@click.group()
def cli():
    pass


@cli.command('run')
def run():
    # Read in the configuration
    config = read_config()
    # Instantiate a filter
    filters = Filters(config['sieve'])
    # Instantiate a processor
    processor = Processor(config['processor'], config['redis'])
    # Instantiate a inlet
    inlet = Inlet(config['redis'], filters, processor)
    # Open the flood gates
    inlet.open()


@cli.command('hosts')
def hosts():
    pull_host_lists()


@cli.command('whitelist')
def whitelist():
    process_whitelist()

if __name__ == '__main__':
    cli()
