redis:
  host: valkey
  port: 6379
  channel: turkeybite
  password_file: /run/secrets/valkey_password
  db: 0
  host_list_db: 1

sieve:
# browserbeat rules
  browserbeat:
    ignore:
      clients:
        # - 192.168.1.1
        # - somehost-to-ignore
      users:
        # - root
      domains:
        # - whitelisted-domain.com
      hosts:
        # - www.whitelisted-domain.com

# DNS packagebeat rules
  drop_replies: true
  drop_error_packets: true
  ignore:
    # Ignore entire domains
    domains:
      # - whitelisted-domain.com
      - 10.in-addr.arpa
      - 192.168.in-addr.arpa
      - default.svc
      - kubernetes.default
    # Ignore specific client IP addresses
    clients:
      - 127.0.0.1
    # Ignore specific hostnames
    hosts:
      - kubernetes.default.svc

processor:
  dns:
    lookup_ips: true
    resolvers:
      - 172.172.0.100
  elastic:
    enable: true
    index_prefix: tb-index
    hosts:
      - uri: https://opensearch:9200
        username: admin
        password: Changeit12345!
  syslog:
    # Syslog UDP
    enable: false
    port: 514
    host: graylog