services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: ${OPENSEARCH_HOST:-opensearch}
    restart: unless-stopped
    expose:
      - "${OPENSEARCH_PORT:-9200}"
      - "${OPENSEARCH_PERFORMANCE_PORT:-9600}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - TZ
      - bootstrap.memory_lock
      - node.name
      - discovery.type
      - OPENSEARCH_JAVA_OPTS
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD
      - OPENSEARCH_CLUSTER_NAME
    networks:
      - tb-net
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f https://localhost:9200/_cluster/health?pretty -u admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD} --insecure || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    restart: unless-stopped
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - ${OPENSEARCH_DASHBOARD_PORT:-5601}:5601
    environment:
      - OPENSEARCH_HOSTS
    networks:
      - tb-net
